-- Partner-specific collaboration shirt configuration.
--
-- The live schema now bootstraps these columns lazily in code, so this
-- migration is intentionally a no-op to avoid failing on databases where the
-- columns were already added out-of-band.
